// Generates data/dow30.js and data/nasdaq100.js — realistic *sample* data for the
// Dow Jones Industrial Average (30) and Nasdaq-100, for all 7 periods. Used as the
// fallback when the live Yahoo-fed Worker is unavailable.
//
//   node scripts/gen_sample_us.mjs
//
// Same modeling idea as gen_sample.mjs: a constituent's point contribution ≈
// (its weight proxy) × (its % change). For the price-weighted Dow the weight proxy
// is share price; for the cap-weighted Nasdaq-100 it is the index cap weight (%).
// The visualization consumes window.HEATMAP_SAMPLE[index]. Values are illustrative.

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DOW30, NASDAQ100 } from '../server/us-constituents.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ---- deterministic RNG (mulberry32) so output is reproducible ---------------
function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
function makeGauss(rand) {
  return (mu = 0, sd = 1) => {
    let u = 0, v = 0;
    while (u === 0) u = rand();
    while (v === 0) v = rand();
    return mu + sd * Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
  };
}

// per-period market character (US markets) — drift/vol in %, cap clamps |change|.
const AS_OF = '2026-07-28T16:00:00-04:00';
const PERIODS = {
  '1D':  { drift: -0.8, vol: 1.9, cap: 11 },
  '1W':  { drift:  0.4, vol: 3.0, cap: 18 },
  '1M':  { drift:  2.4, vol: 5.0, cap: 30 },
  '3M':  { drift:  5.5, vol: 8.0, cap: 45 },
  '6M':  { drift:  8.0, vol: 12,  cap: 65 },
  'YTD': { drift: 11.0, vol: 15,  cap: 85 },
  '1Y':  { drift: 16.0, vol: 22,  cap: 140 },
};

// contribution scale keeps the tooltip numbers in a pleasant range per index.
function build(constituents, { seed, contribScale }) {
  const out = {};
  const sectors = [...new Set(constituents.map((c) => c[2]))];
  let pSeed = seed;
  for (const [pkey, cfg] of Object.entries(PERIODS)) {
    const rand = rng(pSeed++);
    const g = makeGauss(rand);
    const sectorShock = {};
    for (const s of sectors) sectorShock[s] = g(0, cfg.vol * 0.45);
    const list = constituents.map(([code, name, sector, w]) => {
      const raw = cfg.drift + sectorShock[sector] + g(0, cfg.vol);
      const changePct = Math.max(-cfg.cap, Math.min(cfg.cap, raw));
      const contribution = w * changePct * contribScale; // signed index points
      return {
        code, name, sector,
        changePct: Math.round(changePct * 100) / 100,
        contribution: Math.round(contribution * 100) / 100,
      };
    });
    out[pkey] = { asOf: AS_OF, constituents: list };
  }
  return out;
}

// ---- timeline: last 5 trading days (daily change), fixed footprint ----------
// Area (contribution) is pinned to each name's fixed weight proxy (share price for
// the Dow, cap weight% for the Nasdaq) so the layout holds still across frames and
// only height/color (that day's change%) animate. 5 consecutive ET sessions.
const TL_DATES = ['2026-07-22', '2026-07-23', '2026-07-24', '2026-07-27', '2026-07-28'];
function buildTimeline(constituents, seed) {
  const frames = [];
  const sectors = [...new Set(constituents.map((c) => c[2]))];
  let pSeed = seed;
  for (const date of TL_DATES) {
    const rand = rng(pSeed++);
    const g = makeGauss(rand);
    const drift = g(0, 0.5);
    const sectorShock = {};
    for (const s of sectors) sectorShock[s] = g(0, 0.8);
    const list = constituents.map(([code, name, sector, w]) => {
      const changePct = Math.max(-8, Math.min(8, drift + sectorShock[sector] + g(0, 1.2)));
      return {
        code, name, sector,
        changePct: Math.round(changePct * 100) / 100,
        contribution: Math.round(w * 100) / 100,    // FIXED size (weight) → stable layout
      };
    });
    frames.push({ asOf: date, constituents: list });
  }
  return { frames };
}

function emit(globalKey, data, outName) {
  const banner = `// AUTO-GENERATED by scripts/gen_sample_us.mjs — sample data, not real quotes.
// Replaced at runtime by the live Yahoo-fed Worker; this is the offline fallback.
// Shape: window.HEATMAP_SAMPLE['${globalKey}'][period] = { asOf, constituents:[{code,name,sector,changePct,contribution}] }
`;
  const body = `window.HEATMAP_SAMPLE = window.HEATMAP_SAMPLE || {};\nwindow.HEATMAP_SAMPLE['${globalKey}'] = ${JSON.stringify(data)};\n`;
  const outPath = resolve(__dirname, `../public/data/${outName}`);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, banner + body);
  const n = data['1D'].constituents.length;
  console.log(`wrote ${outPath} — ${n} constituents × ${Object.keys(data).length} periods`);
}

// Dow: price-weighted → divisor ≈ 0.163 → contribution ≈ price×(%/100)/0.163.
// contribScale ≈ 1/100/0.163 ≈ 0.06 keeps points on a Dow-like scale.
const dow = build(DOW30, { seed: 22001, contribScale: 0.06 });
dow.TIMELINE = buildTimeline(DOW30, 66001);
emit('DOW30', dow, 'dow30.js');
// Nasdaq-100: cap-weighted → contribution ≈ NDXlevel×weight×(%/100). With NDX≈24000
// and weight in %, contribScale ≈ 24000/100/100 ≈ 2.4.
const ndx = build(NASDAQ100, { seed: 33001, contribScale: 2.4 });
ndx.TIMELINE = buildTimeline(NASDAQ100, 77001);
emit('NASDAQ100', ndx, 'nasdaq100.js');
